Repository citrusframework/citrus-simulator, pull requests merged in 2022-04, with the labels that each got.

#128 chore(deps): include jdk17 compatible jaxb-runtime
  simulator-samples/sample-jms-fax/pom.xml
Labels: dependencies

#133 chore(deps): spring-core upgrade
  .github/workflows/lts.yml
  pom.xml
  simulator-starter/src/main/java/org/citrusframework/simulator/repository/MessageRepositoryCustom.java
  simulator-starter/src/main/java/org/citrusframework/simulator/repository/ScenarioExecutionRepository.java
  simulator-starter/src/main/java/org/citrusframework/simulator/repository/ScenarioExecutionRepositoryCustom.java
Labels: Prio: High, dependencies

#135 pagination-fix
  simulator-starter/src/main/java/org/citrusframework/simulator/repository/MessageRepositoryImpl.java
  simulator-starter/src/main/java/org/citrusframework/simulator/repository/ScenarioExecutionRepositoryImpl.java
  simulator-ui/src/main/resources/static/src/app/components/activity/activity.ts
  simulator-ui/src/main/resources/static/src/app/components/messages/messages.ts
  simulator-ui/src/main/resources/static/src/app/components/shared/date-time.ts
  simulator-ui/src/main/resources/static/src/app/model/filter.ts
  simulator-ui/src/main/resources/static/src/app/styles/filter-section.css
Labels: Type: Bug, TO REVIEW, Prio: Medium, javascript
