Repository citrusframework/citrus-simulator, pull requests merged in 2023-11, with the labels that each got.

#194 chore(simulator-ui): dependency updates
  simulator-ui/package-lock.json
  simulator-ui/package.json
Labels: Prio: High, dependencies, javascript

#196 fix(deps): transitive dependency vulnerabilities
  pom.xml
  simulator-starter/pom.xml
Labels: Prio: High, dependencies

#199 fix(simulator-starter): swagger-api and -ui
  simulator-starter/pom.xml
  simulator-ui/src/main/webapp/swagger-ui/index.html
Labels: Type: Bug, READY, Prio: High, dependencies

#205 fix(#175): Allow multiple rest adapter urlMappings
  simulator-samples/sample-swagger/src/main/java/org/citrusframework/simulator/sample/Simulator.java
  simulator-starter/src/main/java/org/citrusframework/simulator/http/SimulatorRestAdapter.java
  simulator-starter/src/main/java/org/citrusframework/simulator/http/SimulatorRestAutoConfiguration.java
  simulator-starter/src/main/java/org/citrusframework/simulator/http/SimulatorRestConfigurationProperties.java
  simulator-starter/src/main/java/org/citrusframework/simulator/http/SimulatorRestConfigurer.java
  simulator-starter/src/test/java/org/citrusframework/simulator/http/SimulatorRestAutoConfigurationTest.java
  simulator-starter/src/test/java/org/citrusframework/simulator/http/SimulatorRestConfigurationPropertiesMultiUrlIT.java
  simulator-starter/src/test/java/org/citrusframework/simulator/http/SimulatorRestConfigurationPropertiesSingleUrlIT.java
  simulator-ui/src/main/java/org/citrusframework/simulator/ui/config/SecurityConfiguration.java
  simulator-ui/src/test/resources/application.properties
Labels: Type: Feature, Prio: High, java

#208 ui improvements
  simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.html
  simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.spec.ts
  simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.ts
  simulator-ui/src/main/webapp/app/entities/message-header/list/message-header.component.html
  simulator-ui/src/main/webapp/app/entities/message-header/list/message-header.component.spec.ts
  simulator-ui/src/main/webapp/app/entities/message-header/list/message-header.component.ts
  simulator-ui/src/main/webapp/app/entities/message-header/service/message-header.service.ts
  simulator-ui/src/main/webapp/app/entities/message/detail/message-detail.component.html
  simulator-ui/src/main/webapp/app/entities/message/detail/message-detail.component.ts
  simulator-ui/src/main/webapp/app/entities/message/message.model.ts
  simulator-ui/src/main/webapp/app/entities/message/service/message.service.ts
  simulator-ui/src/main/webapp/app/entities/scenario-execution/list/scenario-execution.component.html
  simulator-ui/src/main/webapp/app/entities/scenario-execution/list/scenario-execution.component.ts
  simulator-ui/src/main/webapp/app/entities/test-result/list/test-result.component.html
  simulator-ui/src/main/webapp/app/entities/test-result/list/test-result.component.ts
  simulator-ui/src/main/webapp/app/entities/test-result/test-result.model.ts
Labels: READY, Type: Feature, Prio: High, javascript

#214 docs: advanced concepts
  simulator-docs/src/main/asciidoc/concepts-advanced.adoc
  simulator-docs/src/main/asciidoc/images/database-schema.png
  simulator-docs/src/main/asciidoc/images/database-schema.puml
  simulator-docs/src/main/asciidoc/index.adoc
Labels: READY, Type: Maintenance, documentation

#216 Draft: scenario executions filter
  simulator-ui/src/main/webapp/app/entities/message-header/detail/message-header-detail.component.html
  simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.html
  simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.ts
  simulator-ui/src/main/webapp/app/entities/message-header/list/message-header.component.html
  simulator-ui/src/main/webapp/app/entities/message-header/list/message-header.component.ts
  simulator-ui/src/main/webapp/app/entities/message/detail/message-detail.component.html
  simulator-ui/src/main/webapp/app/entities/message/list/message.component.html
  simulator-ui/src/main/webapp/app/entities/message/list/message.component.ts
  simulator-ui/src/main/webapp/app/entities/scenario-action/list/scenario-action.component.html
  simulator-ui/src/main/webapp/app/entities/scenario-action/list/scenario-action.component.ts
  simulator-ui/src/main/webapp/app/entities/scenario-action/service/scenario-action.service.ts
  simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-execution-detail.component.html
  simulator-ui/src/main/webapp/app/entities/scenario-execution/list/scenario-execution.component.html
  simulator-ui/src/main/webapp/app/entities/scenario-execution/list/scenario-execution.component.ts
  simulator-ui/src/main/webapp/app/entities/scenario-execution/scenario-execution.model.spec.ts
  simulator-ui/src/main/webapp/app/entities/scenario-execution/scenario-execution.model.ts
  simulator-ui/src/main/webapp/app/entities/scenario-parameter/detail/scenario-parameter-detail.component.html
  simulator-ui/src/main/webapp/app/entities/scenario-parameter/list/scenario-parameter.component.html
  simulator-ui/src/main/webapp/app/entities/scenario-parameter/list/scenario-parameter.component.ts
  simulator-ui/src/main/webapp/app/entities/scenario-parameter/service/scenario-parameter.service.ts
  simulator-ui/src/main/webapp/app/entities/test-parameter/detail/test-parameter-detail.component.html
  simulator-ui/src/main/webapp/app/entities/test-parameter/list/test-parameter.component.html
  simulator-ui/src/main/webapp/app/entities/test-parameter/list/test-parameter.component.ts
  simulator-ui/src/main/webapp/app/entities/test-result/detail/test-result-detail.component.html
  simulator-ui/src/main/webapp/app/entities/test-result/list/test-result.component.html
  simulator-ui/src/main/webapp/app/entities/test-result/list/test-result.component.ts
  simulator-ui/src/main/webapp/app/home/test-result-summary.component.html
  simulator-ui/src/main/webapp/app/scenario-result/scenario-execution-filter.component.html
  simulator-ui/src/main/webapp/app/scenario-result/scenario-execution-filter.component.spec.ts
  simulator-ui/src/main/webapp/app/scenario-result/scenario-execution-filter.component.ts
  simulator-ui/src/main/webapp/app/scenario-result/scenario-result.component.html
  simulator-ui/src/main/webapp/app/scenario-result/scenario-result.component.ts
  simulator-ui/src/main/webapp/app/scenario/detail/scenario-detail.component.html
  simulator-ui/src/main/webapp/app/scenario/list/scenario.component.html
  simulator-ui/src/main/webapp/app/shared/date/format-date-time-filter-options.spec.ts
  simulator-ui/src/main/webapp/app/shared/date/format-date-time-filter-options.ts
  simulator-ui/src/main/webapp/i18n/en/scenarioExecution.json
Labels: IN PROGRESS, Type: Feature, Prio: High, javascript

#219 citrus release 4.0.2
  pom.xml
  simulator-archetypes/archetype-jms/src/main/resources/archetype-resources/pom.xml
  simulator-archetypes/archetype-mail/src/main/resources/archetype-resources/pom.xml
  simulator-archetypes/archetype-rest/src/main/resources/archetype-resources/pom.xml
  simulator-archetypes/archetype-swagger/src/main/resources/archetype-resources/pom.xml
  simulator-archetypes/archetype-ws/src/main/resources/archetype-resources/pom.xml
  simulator-archetypes/archetype-wsdl/src/main/resources/archetype-resources/pom.xml
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/dictionary/InboundXmlDataDictionary.java
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/dictionary/OutboundXmlDataDictionary.java
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/dictionary/XmlUtils.java
Labels: READY, Prio: High, dependencies

#221 easy response helpers
  simulator-samples/sample-bank-service/src/main/java/org/citrusframework/simulator/sample/scenario/CalculateIban.java
  simulator-samples/sample-bank-service/src/main/java/org/citrusframework/simulator/sample/scenario/ValidateIban.java
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/dictionary/OutboundXmlDataDictionary.java
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/http/HttpScenarioActionBuilder.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/http/HttpScenarioActionBuilderTest.java
Labels: READY, Type: Feature, TO REVIEW, Prio: Medium, java

#224 chore: cleanup send helpers
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/http/HttpScenarioActionBuilder.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/http/HttpScenarioActionBuilderTest.java
Labels: Type: Enhancement, READY, Prio: High, java
