Repository citrusframework/citrus-simulator, pull requests merged in 2024-01, with the labels that each got.

#232 fix(#230): Multiple scenario calls on scenarios overriding run method
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/impl/DefaultScenarioExecutorServiceImpl.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/DefaultScenarioExecutorServiceImplTest.java
Labels: Type: Bug, Prio: High

#235 sortable scenario executions
  simulator-ui/src/main/webapp/app/entities/scenario-execution/list/scenario-execution.component.spec.ts
  simulator-ui/src/main/webapp/app/entities/scenario-execution/list/scenario-execution.component.ts
  simulator-ui/src/main/webapp/app/scenario-result/scenario-result.component.html
  simulator-ui/src/main/webapp/app/scenario-result/scenario-result.component.spec.ts
  simulator-ui/src/main/webapp/app/scenario-result/scenario-result.component.ts
  simulator-ui/src/main/webapp/app/scenario/list/scenario.component.html
  simulator-ui/src/main/webapp/app/scenario/list/scenario.component.spec.ts
  simulator-ui/src/main/webapp/app/scenario/list/scenario.component.ts
Labels: Type: Enhancement, READY, Prio: High, javascript

#236 feat(simulator): search by scenario name
  simulator-docs/src/main/asciidoc/rest-api.adoc
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/MessageHeaderResource.java
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/MessageResource.java
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/ScenarioActionResource.java
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/ScenarioExecutionResource.java
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/ScenarioParameterResource.java
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/ScenarioResource.java
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/TestParameterResource.java
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/TestResultResource.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/events/ScenariosReloadedEventIT.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/repository/MessageHeaderRepositoryIT.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/repository/MessageRepositoryIT.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/repository/ScenarioActionRepositoryIT.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/repository/ScenarioParameterRepositoryIT.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/MessageHeaderServiceImplTest.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/MessageServiceImplTest.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/ScenarioActionServiceImplTest.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/ScenarioExecutionServiceImplTest.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/ScenarioParameterServiceImplTest.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/ScenarioResourceIT.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/ScenarioResourceTest.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/util/PaginationUtilTest.java
Labels: Type: Feature, Prio: High, java
