Repository citrusframework/citrus-simulator, pull requests merged in 2024-04, with the labels that each got.

#257 update node and npm, including modules
  pom.xml
  simulator-ui/package-lock.json
  simulator-ui/package.json
Labels: READY, Type: Maintenance, Prio: High, dependencies, javascript

#263 take google fonts offline
  .github/workflows/frontend.yml
  simulator-ui/.npmrc
  simulator-ui/package-lock.json
  simulator-ui/src/main/java/org/citrusframework/simulator/ui/config/SimulatorUiConfigurationProperties.java
  simulator-ui/src/main/webapp/content/fonts/open-sans-v40-latin-300italic.woff2
  simulator-ui/src/main/webapp/content/fonts/open-sans-v40-latin-500italic.woff2
  simulator-ui/src/main/webapp/content/fonts/open-sans-v40-latin-600italic.woff2
  simulator-ui/src/main/webapp/content/fonts/open-sans-v40-latin-700italic.woff2
  simulator-ui/src/main/webapp/content/scss/vendor.scss
Labels: Type: Maintenance, Prio: High, javascript

#262 fix(#261): open window in new tab
  simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.html
  simulator-ui/src/main/webapp/app/entities/message/list/message.component.html
  simulator-ui/src/main/webapp/app/entities/scenario-action/list/scenario-action.component.html
  simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/message-table.component.html
  simulator-ui/src/main/webapp/app/entities/scenario-execution/list/scenario-execution.component.html
  simulator-ui/src/main/webapp/app/entities/scenario-parameter/list/scenario-parameter.component.html
  simulator-ui/src/main/webapp/app/entities/test-parameter/list/test-parameter.component.html
  simulator-ui/src/main/webapp/app/entities/test-result/list/test-result.component.html
  simulator-ui/src/main/webapp/app/home/test-result-summary.component.html
  simulator-ui/src/main/webapp/app/scenario/list/scenario.component.html
Labels: Type: Bug, TO REVIEW, Prio: High, javascript
