Repository citrusframework/citrus-simulator, pull requests merged in 2024-02, with the labels that each got.

#240 scenario execution details
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/ScenarioExecution.java
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/ScenarioActionService.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/ScenarioActionServiceImplTest.java
  simulator-ui/src/main/webapp/app/core/util/operator.spec.ts
  simulator-ui/src/main/webapp/app/core/util/operators.ts
  simulator-ui/src/main/webapp/app/core/util/sort-parameters.type.ts
  simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.html
  simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.spec.ts
  simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.ts
  simulator-ui/src/main/webapp/app/entities/message-header/list/message-header.component.ts
  simulator-ui/src/main/webapp/app/entities/message/detail/message-detail.component.html
  simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/message-table.component.html
  simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/message-table.component.spec.ts
  simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/message-table.component.ts
  simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-execution-detail.component.html
  simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-execution-detail.component.ts
  simulator-ui/src/main/webapp/app/entities/scenario-execution/scenario-execution.model.ts
Labels: Type: Enhancement, Prio: High, javascript

#243 fix(#242): Support proxied and subclassed scenarios
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/http/HttpRequestAnnotationScenarioMapper.java
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/scenario/ScenarioUtils.java
  simulator-spring-boot/src/main/java/org/citrusframework/simulator/scenario/SimulatorScenario.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/http/HttpRequestAnnotationScenarioMapperIT.java
  simulator-spring-boot/src/test/java/org/citrusframework/simulator/http/HttpRequestAnnotationScenarioMapperTest.java
Labels: Type: Bug, Prio: High

#249 update spring-boot to v3.2.3
  pom.xml
Labels: READY, Type: Maintenance, Prio: High, dependencies
